In [5]:
import NeuralNetworks as nn

In [6]:
!pip install nnfs

In [7]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [8]:
X, y = spiral_data(samples=100, classes=3)

In [9]:
dense1 = nn.Layer_Dense(2, 3)

In [11]:
dense1.forward(X, 1)

In [12]:
print(dense1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.08914123e-04 -5.85314953e-05  1.43452407e-04]
 [ 1.49312911e-04  4.40574662e-05  1.80027407e-04]
 [ 1.08196418e-04  1.92345672e-04  1.08984199e-04]
 [ 2.87377418e-04  1.03173174e-04  3.44033145e-04]]


In [13]:
X

array([[-0.00000000e+00,  0.00000000e+00],
       [-7.47850472e-03,  6.78987277e-03],
       [-1.56240144e-03,  2.01415124e-02],
       [ 1.00831703e-02,  2.85762720e-02],
       [-1.72230484e-03,  4.03673153e-02],
       [ 9.51469248e-03,  4.96007132e-02],
       [ 6.03383279e-02,  5.69041018e-03],
       [ 6.14323781e-02,  3.50078958e-02],
       [ 4.69382906e-03,  8.06716424e-02],
       [ 6.20861929e-02,  6.64060800e-02],
       [ 4.27512681e-02,  9.15170453e-02],
       [ 1.08833003e-01,  2.23842928e-02],
       [ 1.21098990e-01,  5.23574374e-03],
       [ 1.16015246e-01,  6.15109839e-02],
       [ 1.18127850e-01,  7.77416905e-02],
       [ 7.04978139e-02, -1.34115247e-01],
       [ 1.61219983e-01, -1.13093184e-02],
       [ 1.71182795e-01, -1.35365376e-02],
       [ 1.73130960e-01, -5.55294692e-02],
       [ 1.33414902e-01, -1.37961734e-01],
       [ 1.77044313e-01, -9.73009420e-02],
       [ 2.08439196e-01,  3.93511147e-02],
       [ 4.16181856e-02, -2.18290272e-01],
       [ 1.

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [17]:
print(dense1.weights)

[[-0.00842651  0.01055605 -0.01190535]
 [ 0.00675954  0.00300624  0.00801462]]


In [19]:
dense1.biases

array([[0., 0., 0.]])

In [25]:
a =  [-7.47850472e-03,  6.78987277e-03]
b = [-0.00842651, 0.00675954]
c = [0]
f = np.dot(a, np.array(b).T)
g = f + c
g

array([0.00010891])

In [31]:
e = [1, 2, 3]
np.expand_dims(np.array(e), axis=0)

array([[1, 2, 3]])

In [33]:
activation1 = nn.Activation_Sigmoid()

In [35]:
activation1.forward(dense1.output, 1)

In [36]:
print(activation1.output[:5])

[[0.5        0.5        0.5       ]
 [0.50002723 0.49998537 0.50003586]
 [0.50003733 0.50001101 0.50004501]
 [0.50002705 0.50004809 0.50002725]
 [0.50007184 0.50002579 0.50008601]]


In [37]:
s = 1/(1+np.exp(-g))

In [38]:
s

array([0.50002723])

In [85]:
loss_function = nn.Loss_CategoricalCrossentropy()


In [86]:
dense2 = nn.Layer_Dense(3, 3)


In [87]:
dense2.forward(activation1.output, 1)

In [88]:
activation2 = nn.Activation_Softmax()

In [89]:
activation2.forward(dense2.output, 1) 

In [90]:
print(activation2.output[:5])

[[0.33175373 0.33305527 0.335191  ]
 [0.33175371 0.3330551  0.3351912 ]
 [0.33175366 0.33305514 0.3351912 ]
 [0.33175363 0.33305532 0.33519106]
 [0.33175358 0.33305504 0.33519137]]


In [91]:
loss = loss_function.calculate(activation2.output, y)

AttributeError: 'Loss_CategoricalCrossentropy' object has no attribute 'accumulated_sum'